In [ ]:
<h1></h1>
<a></a>

In [ ]:
<h2></h2>


In [1]:
N = int(input())
print(chr(N))

97
a


In [10]:
N,K = map(int, input().split())
A = [int(i) for i in input().split()]
B = [int(i) for i in input().split()]
m=0
ind=[]
for i in range(N):
    if m < A[i]:
        m=A[i]
        ind[:]=[]
        ind.append(i+1)
        indind=1
    elif m == A[i]:
        ind.append(i+1)
    
indand=set(ind) & set(B)
if len(indand)==0:
    print('No')
else:
    print('Yes')

5 3
 6 8 10 7 10
2 3 4
yes


In [ ]:
<h2></h2>


In [39]:
N = int(input())
str=[]
num=[[0]*N]*10
m=0
t=0
for i in range(N):
    str.append(input())
    for j in range(10):
        print(str[i][j])
        print(num[int(str[i][j])])
        num[int(str[i][j])][i]=j
        print(num[int(str[i][j])])
        print(num)
print(num)
for i in range(10):
    list.sort(num[i])
    print(num[i])
    lst=-1
    mn=0
    a=0
    ma=0
    for j in range(N):
        if lst == num[i][j]:
            t+=10
            a=a+1
            if ma<= a:
                mn=num[i][j]
        else:
            a=0
        lst=num[i][j]
    if mn==0:
        t=num[i][N-1]
    else:
        t=mn
    t+=mn
    if m> t:
        m=t
        t=0
    else:
        t=0
print(m)


3
8124690357
8
[0, 0, 0]
[0, 0, 0]
[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
1
[0, 0, 0]
[1, 0, 0]
[[1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0]]
2
[1, 0, 0]
[2, 0, 0]
[[2, 0, 0], [2, 0, 0], [2, 0, 0], [2, 0, 0], [2, 0, 0], [2, 0, 0], [2, 0, 0], [2, 0, 0], [2, 0, 0], [2, 0, 0]]
4
[2, 0, 0]
[3, 0, 0]
[[3, 0, 0], [3, 0, 0], [3, 0, 0], [3, 0, 0], [3, 0, 0], [3, 0, 0], [3, 0, 0], [3, 0, 0], [3, 0, 0], [3, 0, 0]]
6
[3, 0, 0]
[4, 0, 0]
[[4, 0, 0], [4, 0, 0], [4, 0, 0], [4, 0, 0], [4, 0, 0], [4, 0, 0], [4, 0, 0], [4, 0, 0], [4, 0, 0], [4, 0, 0]]
9
[4, 0, 0]
[5, 0, 0]
[[5, 0, 0], [5, 0, 0], [5, 0, 0], [5, 0, 0], [5, 0, 0], [5, 0, 0], [5, 0, 0], [5, 0, 0], [5, 0, 0], [5, 0, 0]]
0
[5, 0, 0]
[6, 0, 0]
[[6, 0, 0], [6, 0, 0], [6, 0, 0], [6, 0, 0], [6, 0, 0], [6, 0, 0], [6, 0, 0], [6, 0, 0], [6, 0, 0], [6, 0, 0]]
3
[6, 0, 0]
[7, 0, 0]
[[7, 0, 0], [7, 0, 0], [7, 0, 0], 

KeyboardInterrupt: Interrupted by user

In [46]:
import numpy as np
N = int(input())
str=[]
num=np.zeros((10,N))

m=0
t=0
for i in range(N):
    str.append(input())
    for j in range(10):
        num[int(str[i][j])][i]=j
        

for i in range(10):
    num[i]=np.sort(num[i])
    lst=-1
    mn=0
    a=0
    ma=0
    for j in range(N):
        if lst == num[i][j]:
            t+=10
            a=a+1
            if ma<= a:
                mn=num[i][j]
        else:
            a=0
        lst=num[i][j]
    if mn==0:
        t=num[i][N-1]
    else:
        t=mn
    t+=mn
    if m> t:
        m=t
        t=0
    else:
        t=0
print(m)


3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
1937458062
1
[0. 0. 0.]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
9
[0. 0. 0.]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
3
[0. 0. 0.]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
7
[0. 0. 0.]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [3. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
4
[0. 0. 0.]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [2. 0. 0.]
 [4. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [3. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
5
[0. 0. 0.]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [2. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [0. 0. 0.]
 [3. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0

In [ ]:
<h2></h2>
